"""add privilege tracking to users

Revision ID: 44810adc04d8
Revises: 4f603717196f
Create Date: 2026-06-13 21:05:27.766438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44810adc04d8'
down_revision = '4f603717196f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_primary_admin', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('promoted_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('promoted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('demoted_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_users_promoted_by', 'users', ['promoted_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_promoted_by', type_='foreignkey')
        batch_op.drop_column('demoted_at')
        batch_op.drop_column('promoted_at')
        batch_op.drop_column('promoted_by')
        batch_op.drop_column('is_primary_admin')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
